/* initialization constants */

export const ANIMATION_FINISHED = 'ANIMATION_FINISHED';
export const VIEW_READY = 'WEBSCENE_LOADED';
export const VISUALIZATION_CHANGED = 'VISUALIZATION_CHANGED';
export const SELECTION_CHANGED = 'SELECTION_CHANGED';
